### ISSUE TITLE
Support relative URI references

### ISSUE THREAD

**Issue by akkie** [softwaremill/sttp-model#12]
Hi,

with the current implementation, a `Uri` instance can only be constructed with a scheme. The RFC 3986 allows also to define relative URI references which can start with two slashes (` //example.com`) for a network-path reference, with a single slash (`/some-path`) for a absolute-path reference or without a slash (`some-path`) for a relative-path reference.

https://tools.ietf.org/html/rfc3986#section-4.2

**Comment by adamw** [comment]
Released in https://github.com/softwaremill/sttp-model/releases/tag/v1.2.0-RC10 via #51
