### ISSUE TITLE
MediaType.parse fails on scala-native

### ISSUE THREAD

**Issue by adamw** [softwaremill/sttp-model#188]
`MediaType.parse("text/plain; charset=utf-8")` gives:

```
Left("Parameter is not formatted correctly: "; charset=utf-8" for: "text/plain; charset=utf-8"")
```

instead of the result.
Probably the reason why `MediaTypeTest` is in `scalajvm`, not in the shared `scala` test sources.

**Comment by Pask423** [comment]
Test file moved in #192

**Comment by Pask423** [comment]
Seems that is should work in scala-native since 0.4.5 according to https://scala-native.readthedocs.io/en/latest/changelog/0.4.5.html
