### ISSUE TITLE
Improve performance of UriInterpolator

### ISSUE THREAD

**Issue by danilbykov** [softwaremill/sttp-model#196]
I often see stack traces of UriInterpolator inside JFR performance profiles. It looks like parsing and interpolation of URLs takes considerable amount of CPU.

I did dirty changes (not ready for pull request yet) inside UriInterpolator and got 3x or 4x performance improvement.

Here is result of my benchmarks
```
[info] Benchmark                                   Mode  Cnt       Score   Error  Units
[info] InterpolatorBenchmark.longUrlCurrent       thrpt    2   82954,476          ops/s
[info] InterpolatorBenchmark.longUrlFast          thrpt    2  236963,125          ops/s
[info] InterpolatorBenchmark.simpleUrlCurrent     thrpt    2  111629,426          ops/s
[info] InterpolatorBenchmark.simpleUrlFast        thrpt    2  413596,768          ops/s
[info] InterpolatorBenchmark.urlWithQueryCurrent  thrpt    2   53065,576          ops/s
[info] InterpolatorBenchmark.urlWithQueryFast     thrpt    2  191607,313          ops/s
```

Basically I did two main changes:
1. Inside Tokenizers I collect tokens in java.util.ArrayList instead of Vector
1. For UriBuilder I wrote structure similar to View from scala2.13 and create Uri without Vectors

So I mainly removed allocations of Vectors. Of course code looks more complex but I think performance gain is considerable. What do you think? Are you interested in these changes?

**Comment by adamw** [comment]
Interesting! :) Yes, if you could create a PR, please do
