### ISSUE TITLE
`uri` interpolator does not URL-encode embedded URLs

### ISSUE THREAD

**Issue by benrbray** [softwaremill/sttp-model#207]
I'm not sure if this is a bug, or if I am misunderstanding how the `uri` interpolator is meant to be used.  The docstring for the `uri` string interpolator says:

> Any values embedded in the URI using the `${...}` syntax will be URL-encoded, taking into account the context.  Parts of the URI given as literal strings (not embedded values), are assumed to be URL-encoded and thus will be decoded when creating the `Uri` instance.

Accordingly, I wrote the following, expecting the `exampleUrl` to be url-encoded as part of the query string, but the result was not what I expected:

```scala
import sttp.client3._

val exampleUrl = "https://example.org?foo=5&bar=20"
println(uri"https://foo.org?redirect=${exampleUrl}")
// https://foo.org?redirect=https://example.org?foo%3D5%26bar%3D20
```

I expected the following behavior instead:

```scala
import java.net.URLEncoder

val y = URLEncoder.encode(exampleUrl, "UTF-8")
println(s"https://foo.org?redirect=${y}") 
// https://foo.org?redirect=https%3A%2F%2Fexample.org%3Ffoo%3D5%26bar%3D20
```

Is this a bug?  Or is there another way to achieve the desired result with `sttp`?  Thanks!

**Comment by adamw** [comment]
That's the correct behavior, following the escaping rules defined in [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986). For example, in the query parameter, `:` doesn't need to be escaped, but `=` needs to.

You can change the escaping behavior to escape everything in the query, regardless of context, by calling `myUri.querySegmentsEncoding(QuerySegmentEncoding.All)`
