### ISSUE TITLE
Issue Encoding the : Colon Character Using the Uri class

### ISSUE THREAD

**Issue by jackdanisewicz** [softwaremill/sttp-model#212]
Hi all, I am trying to encode a URL using the Uri class to represent this Uri: `https://example.com/form1%2014%3A58%3A05.282203.pdf`. The decoded URL looks like ``https://example.com/form1 14:58:05.282203.pdf``.

I am having an issue when passing in the encoded URL to the Uri interpolator as an embedded string; the `%3A` escape character is decoding to a colon `:` but it is not encoding back to the `%3A`. When I try passing in the encoded URL as a literal string, the same thing happens .. the `%3A` is decoded to the `:` character and not encoded back to `%3A`. 

Is the Uri class able to encode the `:` character or any of the reserved characters?

I see the option for custom encoding options on queries but I do not see a custom encoding option for the path.

Thanks``

**Comment by adamw** [comment]
See: https://sttp.softwaremill.com/en/latest/model/uri.html#faq-encoding-decoding-uri-components

**Comment by jackdanisewicz** [comment]
Thank you, it still seems unclear to me whether it is possible to encode the `:`. When I create a separate path segment with the `:` it is not encoded.

**Comment by adamw** [comment]
Sure, just use `.pathSegmentsEncoding(Uri.QuerySegmentEncoding.All)` as in the linked doc

**Comment by jackdanisewicz** [comment]
Unfortunately using QuerySegmentEncoding on my path resolves spaces differently so may need to explore something else .. thanks for your help though.

**Comment by adamw** [comment]
The parameter to `pathSegmentsEncoding` is a function `String => String` so you can plug in any encoding logic you like :) This includes passing `Rfc3986.encode(...)(_)` or java's `URLEncoder.encode`.
