### ISSUE TITLE
Datetime formatting isn't suitable when used with an http4s server

### ISSUE THREAD

**Issue by braginxv** [softwaremill/sttp-model#237]
There is a problem arising when cookie's datetime is formatted. This format isn't suitable for http4s server, cuz it uses the first variant of Datetime formating described in https://www.rfc-editor.org/rfc/rfc2616#page-21 (date1), where a day of a month is encoded with two digits. For instance, sttp produces the following formatted cookie:
`"access=cipher1; Expires=Fri, 6 Jan 2023 07:28:00 GMT; Path=/path; Secure; HttpOnly; SameSite=Strict"`
whereas http4s expects
`"access=cipher1; Expires=Fri, 06 Jan 2023 07:28:00 GMT; Path=/path; Secure; HttpOnly; SameSite=Strict"`
and therefore http4s cannot parse cookies generated by sttp. Propably this ussue is actual for other servers as well.

The wrong formatting happens here:
https://github.com/softwaremill/sttp-model/blob/7c7d0501a86de6434b33f837c3aeec99c8a2da67/core/src/main/scala/sttp/model/Header.scala#L168

**Comment by adamw** [comment]
Thanks - it seems that the date1 format also requires a leading `0` in case of single-digit dates. Maybe you would be willing to create a PR?

**Comment by braginxv** [comment]
Ok, I'll try to fix it
