### ISSUE TITLE
Url with configurable encoding

### ISSUE THREAD

**Issue by kusamakura** [softwaremill/sttp-model#49]
Hi!

Our team has been thinking of migrating to sttp in the near future, but one blocker that we encountered is that we need a way to send a request with query string parameters _without_ doing any encoding. Unfortunately it's to a server we have no control over.

Maybe it's possible to add another `toString`-like method that takes in a config object, one that defines how the Uri will be rendered? But I realize that this should also be propagated into `sttp` when making requests, so perhaps this config object can be added into the Uri model itself, and then specified through, say, `Uri.parse`. Then the `toString` method can respect those rendering options (and would therefore be propagated into `sttp` without making any changes there, apart from a version update).

Let me know if this is reasonable – I'll be happy to discuss options and open a PR for this.

**Comment by adamw** [comment]
Do you need parsing or only serialisation? There's already the `.querySegment` method, which allows you to add a segment with arbitrary encoding, e.g.:

```scala
uri"http://example.com/path".querySegment(QuerySegment.Plain("won't be encoded", identity))
```

**Comment by kusamakura** [comment]
@adamw My bad for not seeing that feature. That works perfectly for us! Thanks. I'm closing this if you don't mind.

**Comment by adamw** [comment]
No worries, good that the problem is already resolved :)
