### ISSUE TITLE
Trouble parsing and requesting a specific URL

### ISSUE THREAD

**Issue by jadlr** [softwaremill/sttp-model#64]
I'm writing a tool that runs through a ton of urls and checks if they return 200 OK

I have this URL which works in the browser: (domain and token are fake, but of the same type of chars)
`https://sub.domain.net/shls/dch/354/h264_,LOW_THREE,LOW_TWO,LOW_ONE,MEDIUM_TWO,MEDIUM_ONE,HIGH,VERY_HIGH_ONE,.mp4.urlset/master.m3u8?token=exp=1612378540~acl=/shls/dch/354/*~hmac=adc3b3992ed1e0f95372e37d4b21b23ac426d3c130542bd6b363e0`

I get a 403 and investigated further: 

```scala
  val url: String =
    "https://sub.domain.net/shls/dch/354/h264_,LOW_THREE,LOW_TWO,LOW_ONE,MEDIUM_TWO,MEDIUM_ONE,HIGH,VERY_HIGH_ONE,.mp4.urlset/master.m3u8?token=exp=1612378540~acl=/shls/dch/354/*~hmac=adc3b3992ed1e0f95372e37d4b21b23ac426d3c130542bd6b363e0"

  val uri = Uri.parse(url)

  uri.foreach(println)
```

returns: 
`https://sub.domain.net/shls/dch/354/h264_,LOW_THREE,LOW_TWO,LOW_ONE,MEDIUM_TWO,MEDIUM_ONE,HIGH,VERY_HIGH_ONE,.mp4.urlset/master.m3u8?token=exp&token=1612378540~acl&token=/shls/dch/354/*~hmac&token=adc3b3992ed1e0f95372e37d4b21b23ac426d3c130542bd6b363e0`

There seems to be an issue when parsing weird query strings. Note inserted `&token=.

**Comment by jadlr** [comment]
The weird thing about the query is the `=` in the token value.

I checked `java.net.URI` and it parses the url without trouble.

**Comment by adamw** [comment]
This is now released in 1.3.3. Note that I've retained the behavior, which by default %-encodes the `=` sign in query segment values (as this is what I think *most* people & parsers expect).

You can quite easily change the encoding for query segments, though, having the parsed `Uri` instance:

```scala
uri.querySegmentsEncoding(Uri.QuerySegmentEncoding.StandardValue)
```

**Comment by jadlr** [comment]
That means I have to know about how the `Uri` looks like, right?

What I'd like to do is just request `Uri`s as is. I'm parsing JSON that contains a lot of urls and I'm then checking if these links return a 200.

Is it possible to parse a Uri and use it as is?

**Comment by jadlr** [comment]
I think it should be possible to parse `Uri`s that I know are correctly encoded and request them, without knowing specifics of the uri.

**Comment by adamw** [comment]
Yes, I understand that requirements, but it's quite difficult to achieve using the current approach, where `Uri` stores the various segments in a decoded form. On one hand, this allows introspection, but on the other means that converting it to a serialised form encodes all of the components. Which might not yield *exactly* the same results as the original.

On way would be to optionally store an `original` field with the original serialised form. However:
* it would be *only* filled when parsing an uri given as a string as a whole
* any operation on the uri (adding a query parameter, path, fragment), would forget the original seralised form and revert to the usual serialisation

Hence I'm not so sure that would that useful.

**Comment by jadlr** [comment]
Ok, thanks for the clarification! 

Would it be a lot of work to add req functions that work on `java.net.URI` without parsing them. 
Since i cannot know specifics of the Uris before requesting them in my use case, I'd need something like that. 

But I can understand if that is not something this lib wants to offer! But it would be cool, if you could add a warning somewhere, because I think there is often a need to request Uris you don't know the structure of.

**Comment by adamw** [comment]
Adding a `java.net.URI`-based variant of requests would create a whole parallel universe of all model classes. Rather undoable unfortunately.

If you need to pass the URIs *exactly* as given in a string, then maybe the `original` feature would work for you - as it would override the serialisation mechanism. Otherwise, the URIs produced shuold be equivalent - as an URI-parsing library is usually quite forgiving when it comes to what is encoded and what is not, as clients rarely follow the RFC (`java.net.URI` being a prime example ;) )

**Comment by jadlr** [comment]
Thanks for taking the time to answer! 

I'll have to look deeper into the problem to be able to understand what would help me best, but the `original` feature sounds good.

**Comment by adamw** [comment]
Thinking a bit more about it the `original`, I think it might bring more problems than solutions ;) As every time the `Uri` is modified, we need to reset the original form (if one is specified). This means that `Uri` would cease to be an ordinary case class where you can `.copy` a field to get a modified instance ... as copying would have to somehow trigger reseting.

An alternative, is to capture the original form (if any) in the parser, and supply an encoding function to the segments which uses that original form if the segment is unchanged. But that's still something to explore. Please open another issue if you would still required "intact" URIs to be passed.

And finally an ugly hack, in how you can make an `Uri` serialise to whatever you want:

```scala
new Uri(Some("http"), None, Uri.EmptyPath, Nil, None) {
  override def toString: String = "xyz"
}
```

it hurts to look at, but if your server absolutely requires a given form of an `Uri`, it might be the only choice currently.

**Comment by jadlr** [comment]
:smile: Nice hack. 

If I'm the only one with that requirement, don't bother. The tool I'm writing is tiny and I can live with that hack.

**Comment by jadlr** [comment]
I'm just thinking that this has potential for nasty bugs in case you write a client that has absolutely no control over the URLs it processes.

**Comment by adamw** [comment]
Hard to say :) If you could create the issue, we can leave it open and see if there are others interested in that functionality.

**Comment by adamw** [comment]
> I'm just thinking that this has potential for nasty bugs in case you write a client that has absolutely no control over the URLs it processes.

Maybe, but then also you very often extend the URI in some way, which requires parsing and re-serialising it anyway. And it's not that we break the URI in any way, we just sometimes serialise it to a different string that's equivalent "up to decoding"

**Comment by jadlr** [comment]
> Hard to say :) If you could create the issue, we can leave it open and see if there are others interested in that functionality.

I'll finish up my work and see if I can get to it.

Thanks again for your support :+1:
